# Generated by Django 4.0.2 on 2022-02-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_lname_student_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Contact',
        ),
    ]
