# Generated by Django 4.0.2 on 2022-02-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Emails',
        ),
    ]
