# Generated by Django 4.0.2 on 2022-02-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_contact_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
