# Generated by Django 4.0.2 on 2022-02-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
