# Generated by Django 4.0.2 on 2022-02-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
