# Generated by Django 4.0.2 on 2022-02-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rename_books_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
