# Generated by Django 4.0.2 on 2022-02-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_contact_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='id',
        ),
    ]
