# Generated by Django 4.0.2 on 2022-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=100)),
                ('authorname', models.CharField(max_length=100)),
                ('bookdesc', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='product_images')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
