# Generated by Django 4.0.2 on 2022-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('expiry', models.CharField(max_length=100)),
                ('security', models.CharField(max_length=200)),
                ('postal', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Orders and Payment',
            },
        ),
    ]
