# Generated by Django 4.0.2 on 2022-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'O',
            },
        ),
    ]
