# Generated by Django 4.0.2 on 2022-02-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s',
        ),
    ]
